### ISSUE TITLE
request for ircify: video changes as topic changes?

### ISSUE THREAD

**Issue by jamesmanning** [Atte/BerryTweaks#1]
in the logs on pew.cc, video changes can be seen as coming through the irc bridge as topic changes:

    -!- BerryTube changed the topic of #berrytube to: Now Playing: Bullies & Best Friends - PrinceWhateverer (Ft. Scrambles & ShadyVox) - Rainbow & Rooted 

Any chance the ircify tweak could include that?  Doesn't have to show up as a 'topic change', just something that shows the video name (bonus points for video length and url, but I'll take what I can get :smile: )

Thanks!

**Comment by Atte** [comment]
Added as a new "Show video changes" option in ce36fca139f26ced2440cc51850c8a21d4966770 and pushed to production.

**Comment by jamesmanning** [comment]
Thank you!! It's working perfectly!!

![image](https://cloud.githubusercontent.com/assets/225626/12186440/d7a7fbd6-b570-11e5-8b35-86a132c387d0.png)

**Comment by jamesmanning** [comment]
could you please zero-pad seconds if minutes are present and minutes if hours are present?  Just had a video pop up that's 5:02 but displays as 5:2

![image](https://cloud.githubusercontent.com/assets/225626/12186590/588e54ba-b572-11e5-8b83-d3828d4df921.png)

**Comment by jamesmanning** [comment]
nevermind, you already fixed it in chat :smile:
